version: '3'

services:
  nest-app:
    build:
      context: . # Dockerfile's path
    container_name: nest-app
    restart: always
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - mynetwork
    volumes:
      - ./:/app
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - mynetwork
    volumes:
      - db_data:/var/lib/postgresql/data # persist data even if container shuts down
    env_file:
      - .env

volumes:
  db_data:
    name: ERP-API-nestjs-postgreSQL-prisma

networks:
  - mynetwork
