import { Injectable } from '@nestjs/common';
import {
  IsBoolean,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
} from 'class-validator';

@Injectable()
export class UpdateStudentDto {
  @IsOptional()
  @IsString()
  firstName;
  @IsNotEmpty()
  @IsString()
  middleName;
  @IsNotEmpty()
  @IsString()
  lastName;
  @IsNotEmpty()
  @IsString()
  fullName;
  @IsOptional()
  @IsString()
  phone;
  @IsNotEmpty()
  @IsString()
  mobileOne;
  @IsNotEmpty()
  @IsString()
  mobileTwo;
  @IsNotEmpty()
  @IsString()
  emergencyMobile;
  @IsNotEmpty()
  @IsString()
  officeEmail;
  @IsNotEmpty()
  @IsString()
  personalEmail;
  @IsNotEmpty()
  @IsString()
  studentImage;
  @IsNotEmpty()
  @IsString()
  studentSignature;
  @IsNotEmpty()
  @IsNumber()
  nationalId;
  @IsNotEmpty()
  @IsNumber()
  departmentId;
  @IsNotEmpty()
  @IsNumber()
  programmId;
  @IsNotEmpty()
  @IsString()
  dateOfBirth;
  @IsNotEmpty()
  @IsNumber()
  genderId;
  @IsNotEmpty()
  @IsNumber()
  religionId;
  @IsOptional()
  @IsNumber()
  bloodGroupId;
  @IsOptional()
  @IsBoolean()
  maritialStatus;
  @IsOptional()
  @IsString()
  spousName;
  @IsOptional()
  @IsNumber()
  spouseProfe;
  @IsOptional()
  @IsString()
  fatherOrHusbandName;
  @IsOptional()
  @IsNumber()
  fatherOrHusbandProfe;
  @IsOptional()
  @IsString()
  fatherOrHusbandMobile;
  @IsOptional()
  @IsString()
  motherName;
  @IsOptional()
  @IsNumber()
  motherProfe;
  @IsOptional()
  @IsString()
  motherMobile
  @IsNotEmpty()
  @IsNumber()
  @IsOptional()
  @IsString()
  activeStatus
}
